-- Insert rikishi data into Supabase
-- Run this in your Supabase SQL Editor

INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (1, 'Hoshoryu', 'Yokozuna 1 East', 'Yellow', 10, 1, 0, 0, 3, 2, 288.7, 73.2, 26.2, 8);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (2, 'Onosato', 'Yokozuna 1 West', 'Yellow', 7, 1, 0, 0, 5, 0, 390.1, 75.6, 25.1, 7);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (3, 'Kotozakura', 'Ozeki 1 East', 'Yellow', 6, 0, 1, 0, 3, 2, 365.9, 74, 27.7, 2);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (4, 'Daieisho', 'Sekiwake 1 East', 'Blue', 8, 0, 0, 1, 5, 0, 299.1, 70.5, 31.7, 0);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (5, 'Kirishima', 'Sekiwake 1 West', 'Blue', 8, 1, 0, 0, 3, 2, 304.2, 73.6, 29.3, 6);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (6, 'Wakatakakage', 'Sekiwake 2 West', 'Blue', 7, 1, 0, 0, 4, 1, 284.3, 70.9, 30.6, 12);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (7, 'Oshoma', 'Komusubi 1 East', 'Blue', 7, 0, 1, 0, 2, 3, 330.6, 73.6, 28.3, 3);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (8, 'Takayasu', 'Komusubi 1 West', 'Blue', 6, 0, 1, 0, 1, 4, 359.3, 73.6, 35.4, 4);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (9, 'Aonishiki', 'Maegashira 1 East', 'Blue', 6, 1, 0, 0, 4, 1, 275.5, 70.9, 21.3, 3);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (10, 'Wakamotoharu', 'Maegashira 1 West', 'Blue', 6, 0, 1, 0, 1, 4, 315.2, 73.6, 31.8, 2);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (11, 'Oho', 'Maegashira 2 East', 'Blue', 6, 0, 1, 0, 3, 2, 374.7, 75.2, 25.4, 4);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (12, 'Abi', 'Maegashira 2 West', 'Blue', 5, 1, 0, 0, 2, 3, 328.4, 74, 31.2, 0);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (13, 'Onokatsu', 'Maegashira 3 East', 'Blue', 5, 0, 1, 0, 3, 2, 332.8, 72.8, 25.2, 1);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (14, 'Kinbozan', 'Maegashira 3 West', 'Blue', 5, 1, 0, 0, 3, 2, 363.7, 75.2, 28.1, 1);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (15, 'Hakuoho', 'Maegashira 4 East', 'Blue', 5, 0, 1, 0, 5, 0, 343.8, 70.5, 21.9, 0);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (16, 'Tamawashi', 'Maegashira 4 West', 'Blue', 5, 1, 0, 0, 2, 3, 354.8, 74.8, 40.7, 0);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (17, 'Hiradoumi', 'Maegashira 5 East', 'Green', 6, 0, 1, 0, 2, 3, 284.3, 69.7, 25.3, 0);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (18, 'Meisei', 'Maegashira 5 West', 'Green', 6, 0, 1, 0, 3, 2, 332.8, 70.9, 30, 1);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (19, 'Takerufuji', 'Maegashira 6 East', 'Green', 6, 1, 0, 0, 3, 2, 310.8, 72, 26.3, 6);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (20, 'Gonoyama', 'Maegashira 6 West', 'Green', 6, 1, 0, 0, 0, 5, 341.6, 69.3, 27.3, 2);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (21, 'Tobizaru', 'Maegashira 7 East', 'Green', 5, 0, 1, 0, 3, 2, 288.7, 68.9, 33.3, 1);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (22, 'Endo', 'Maegashira 7 West', 'Green', 5, 0, 0, 1, 4, 1, 320.9, 72, 34.8, 0);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (23, 'Sadanoumi', 'Maegashira 8 East', 'Green', 5, 0, 1, 0, 3, 2, 289.2, 72.4, 38.2, 2);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (24, 'Ichiyamamoto', 'Maegashira 8 West', 'Green', 5, 1, 0, 0, 3, 2, 293.1, 73.6, 31.8, 3);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (25, 'Ura', 'Maegashira 9 East', 'Green', 5, 1, 0, 0, 1, 4, 299.7, 68.9, 33.1, 4);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (26, 'Chiyoshoma', 'Maegashira 9 West', 'Green', 5, 0, 1, 0, 0, 5, 260.5, 72, 34, 3);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (27, 'Atamifuji', 'Maegashira 10 East', 'Green', 4, 0, 1, 0, 3, 2, 365.9, 72.8, 22.9, 2);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (28, 'Roga', 'Maegashira 10 West', 'Green', 4, 1, 0, 0, 4, 1, 315.2, 72.4, 26.4, 2);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (29, 'Takanosho', 'Maegashira 11 East', 'Green', 4, 1, 0, 0, 3, 2, 283.2, 71.5, 30.7, 3);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (30, 'Tokihayate', 'Maegashira 11 West', 'Green', 4, 0, 1, 0, 2, 3, 260.1, 70.1, 28.9, 1);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (31, 'Midorifuji', 'Maegashira 12 East', 'Green', 4, 1, 0, 0, 0, 5, 251.3, 67.3, 28.9, 3);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (32, 'Asakoryu', 'Maegashira 12 West', 'Green', 4, 0, 1, 0, 4, 1, 264.5, 69.3, 26.8, 3);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (33, 'Churanoumi', 'Maegashira 13 East', 'White', 5, 0, 1, 0, 1, 4, 286.5, 69.3, 32.2, 0);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (34, 'Shodai', 'Maegashira 13 West', 'White', 5, 1, 0, 0, 2, 3, 330.6, 71.7, 33.7, 0);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (35, 'Kusano', 'Maegashira 14 East', 'White', 5, 1, 0, 0, 0, 0, 330.6, 72.4, 24.1, 4);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (36, 'Fujinokawa', 'Maegashira 14 West', 'White', 5, 0, 0, 0, 0, 0, #VALUE!, #VALUE!, #VALUE!, 2);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (37, 'Kotoshoho', 'Maegashira 15 East', 'White', 4, 1, 0, 0, 0, 0, 317.4, 74, 25.9, 1);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (38, 'Hidenoumi', 'Maegashira 15 West', 'White', 4, 0, 1, 0, 0, 0, 343.8, 72.8, 36.1, 0);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (39, 'Kayo', 'Maegashira 16 East', 'White', 3, 0, 1, 0, 1, 4, 321.8, 66.5, 26, 0);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (40, 'Mitakeumi', 'Maegashira 16 West', 'White', 3, 1, 0, 0, 0, 0, 379.1, 70.5, 32.6, 1);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (41, 'Kotoeiho', 'Maegashira 17 East', 'White', 3, 0, 1, 0, 0, 0, 266.7, 71.7, 22, 0);
INSERT INTO rikishi (id, name, official_rank, ranking_group, draft_value, wins, losses, absences, last_tourney_wins, last_tourney_losses, weight_lbs, height_inches, age, times_picked) VALUES (42, 'Shishi', 'Maegashira 17 West', 'White', 3, 1, 0, 0, 0, 5, 350.4, 75.2, 28.5, 5);

-- Data loading complete!
